'use strict';
const $=id=>document.getElementById(id), months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
let rows=[], currency='INR';
const num=v=>Number(String(v||'0').replace(/,/g,''));
const sum=(data,key)=>data.reduce((a,r)=>a+num(r[key]),0);
const money=v=>`${currency} ${(v/1e6).toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2})}m`;
const pct=v=>v===null?'—':v.toFixed(1)+'%';
const delta=(a,b)=>b?(a-b)/Math.abs(b)*100:null;
const signed=v=>v===null?'—':`${v>0?'+':''}${v.toFixed(1)}`;
function parseCSV(text){const out=[];let row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(value.trim());value='';if(c==='\n'){if(row.some(Boolean))out.push(row);row=[];}}else if(c!=='\r')value+=c;}if(value||row.length){row.push(value.trim());out.push(row);}const heads=out.shift();return out.map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]||''])));}
function totals(data,scenario='Actual'){const r=sum(data,'Revenue '+scenario),c=sum(data,'Total Cost '+scenario);return {r,c,p:r-c,m:r?(r-c)/r*100:null};}
function options(id,values,all){$(id).replaceChildren(...(all?['All',...values]:values).map(v=>new Option(v==='All'?'All '+all:v,v)));}
function filtered(){return rows.filter(r=>r.Country===$('country').value&&($('unit').value==='All'||r['Business Unit']===$('unit').value)&&($('client').value==='All'||r.Client===$('client').value)&&($('month').value==='All'||r.Month===$('month').value));}
function chart(key,title,unit,data){const selected=months.filter(m=>$('month').value==='All'||m===$('month').value);const series=['Actual','Budget','Forecast'].map(s=>selected.map(m=>{const a=data.filter(r=>r.Month===m);return a.length?totals(a,s)[key]:null;}));const vals=series.flat().filter(v=>v!==null);let lo=key==='m'?Math.floor(Math.min(...vals)/5)*5:0,hi=key==='m'?Math.ceil(Math.max(...vals)/5)*5:Math.max(...vals)*1.1;if(!vals.length){lo=0;hi=1;}if(hi===lo)hi=lo+1;const w=650,h=120,l=49,right=18,top=10,bottom=22;const x=i=>selected.length===1?(w+l-right)/2:l+i*(w-l-right)/(selected.length-1);const y=v=>top+(hi-v)/(hi-lo)*(h-top-bottom);let svg='';for(let i=0;i<3;i++){const v=lo+(hi-lo)*i/2,yy=y(v);svg+=`<line x1="${l}" x2="${w-right}" y1="${yy}" y2="${yy}" stroke="#29404a"/><text x="${l-7}" y="${yy+3}" text-anchor="end">${key==='m'?v.toFixed(0)+'%':(v/1e6).toFixed(1)}</text>`;}selected.forEach((m,i)=>svg+=`<text x="${x(i)}" y="${h-4}" text-anchor="middle">${m}</text>`);series.forEach((s,j)=>{let d='',active=false;s.forEach((v,i)=>{if(v===null){active=false;return;}d+=`${active?'L':'M'}${x(i)},${y(v)} `;active=true;});const color=['#d6b875','#9aaebc','#69c5cd'][j];svg+=`<path d="${d}" fill="none" stroke="${color}" stroke-width="2" ${j===1?'stroke-dasharray="5 4"':''}/>`;s.forEach((v,i)=>{if(v!==null)svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${color}"><title>${selected[i]} · ${['Actual','Budget','Forecast'][j]}: ${key==='m'?pct(v):money(v)}</title></circle>`;});});return `<div class="chart-row"><div class="chart-label">${title}<small>${unit}</small></div><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${title}: actual, budget and forecast by month">${svg}</svg></div>`;}
function update(){const data=filtered();currency=rows.find(r=>r.Country===$('country').value).Currency;const a=totals(data),b=totals(data,'Budget');const cards=[['Actual revenue',money(a.r),delta(a.r,b.r),false],['Actual cost',money(a.c),delta(a.c,b.c),true],['Gross profit',money(a.p),delta(a.p,b.p),false],['Gross margin',pct(a.m),a.m===null||b.m===null?null:a.m-b.m,false]];$('kpis').innerHTML=cards.map(([label,v,d,inverse],i)=>`<article class="kpi"><p>${label}</p><strong>${data.length?v:'—'}</strong><small class="${d===null?'':(inverse?d<=0:d>=0)?'good':'bad'}">${signed(d)}${d===null?'':i===3?' pp':'%'} vs budget</small></article>`).join('');$('charts').innerHTML=chart('r','Revenue',currency+' million',data)+chart('c','Cost',currency+' million',data)+chart('m','Gross margin','% of revenue',data);const units=[...new Set(data.map(r=>r['Business Unit']))].map(name=>{const d=data.filter(r=>r['Business Unit']===name);return {name,a:totals(d),b:totals(d,'Budget')};}).sort((x,y)=>y.a.r-x.a.r);const max=Math.max(...units.map(u=>u.a.r),1);$('units').innerHTML=units.map(u=>{const d=delta(u.a.r,u.b.r);return `<div><div class="unit-head">${u.name}<span>${money(u.a.r)}</span></div><div class="track"><i style="width:${u.a.r/max*100}%"></i></div><div class="unit-bottom"><span>GM ${pct(u.a.m)}</span><span class="${d>=0?'good':'bad'}">Rev ${signed(d)}% vs budget</span></div></div>`;}).join('')||'<p>No records match these filters.</p>';const d=delta(a.r,b.r);$('insight').textContent=data.length?`Revenue is ${d===null?'not comparable to budget':Math.abs(d).toFixed(1)+'% '+(d>=0?'above':'below')+' budget'}. ${units[0].name} leads revenue at ${(units[0].a.r/a.r*100).toFixed(1)}% of this selection. Gross margin is ${pct(a.m)}.`:'Choose another filter combination to view performance.';$('scope').textContent=`${$('country').value} · ${currency} only · ${$('month').value==='All'?'Jan–Dec':$('month').value} 2026 · ${data.length.toLocaleString()} records`;}
async function init(){try{const response=await fetch('data/financial_data.csv');if(!response.ok)throw Error('Data unavailable');rows=parseCSV(await response.text());if(!rows.length||!rows[0]['Revenue Actual'])throw Error('Invalid data');options('country',[...new Set(rows.map(r=>r.Country))].sort());options('unit',[...new Set(rows.map(r=>r['Business Unit']))].sort(),'business units');options('client',[...new Set(rows.map(r=>r.Client))].sort(),'clients');options('month',months,'months');$('country').value='India';['country','unit','client','month'].forEach(id=>$(id).addEventListener('change',update));$('reset').onclick=()=>{$('country').value='India';['unit','client','month'].forEach(id=>$(id).value='All');update();};update();}catch(e){$('error').hidden=false;$('error').textContent='Unable to load data. Keep financial_data.csv inside the data folder and open this dashboard through GitHub Pages or a local web server.';}}
$('present').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){$('present').textContent='Use browser full screen (F11)';}};
init();
